package com.vanmoc.shared.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.session.web.http.DefaultCookieSerializer;
import org.springframework.session.web.http.CookieHttpSessionIdResolver;
import org.springframework.session.web.http.HttpSessionIdResolver;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.regex.Pattern;

@Configuration
public class SessionConfig {
    private static final Pattern SESSION_ID = Pattern.compile(
            "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}");

    @Bean
    HttpSessionIdResolver httpSessionIdResolver(DefaultCookieSerializer cookieSerializer) {
        // Cookie values are untrusted. Legacy Tomcat IDs can decode as binary with NULs;
        // only IDs in the UUID format generated by Spring Session may reach JDBC.
        var delegate = new CookieHttpSessionIdResolver();
        delegate.setCookieSerializer(cookieSerializer);
        return new HttpSessionIdResolver() {
            @Override
            public List<String> resolveSessionIds(HttpServletRequest request) {
                return delegate.resolveSessionIds(request).stream()
                        .filter(id -> SESSION_ID.matcher(id).matches()).toList();
            }
            @Override
            public void setSessionId(HttpServletRequest request, HttpServletResponse response, String sessionId) {
                delegate.setSessionId(request, response, sessionId);
            }
            @Override
            public void expireSession(HttpServletRequest request, HttpServletResponse response) {
                delegate.expireSession(request, response);
            }
        };
    }

    @Bean
    DefaultCookieSerializer cookieSerializer(
            @Value("${server.servlet.session.cookie.secure}") boolean secure,
            @Value("${server.servlet.session.cookie.same-site}") String sameSite) {
        var serializer = new DefaultCookieSerializer();
        serializer.setCookieName("JSESSIONID");
        serializer.setCookiePath("/");
        serializer.setUseHttpOnlyCookie(true);
        serializer.setUseSecureCookie(secure);
        serializer.setSameSite(sameSite);
        return serializer;
    }
}
